name: profissu_dev

services:
  mysql:
    image: mysql:8.1.0
    container_name: profissu_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: 'mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SHOW DATABASES;" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profissu

  redis:
    image: redis:7.4.2
    container_name: profissu_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -h redis -p 6379 -a ${REDIS_PASSWORD} ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profissu

  maildev:
    image: maildev/maildev:2.2.1
    container_name: profissu_maildev
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test: [CMD-SHELL, wget -q --spider http://localhost:1080 || exit 1]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - profissu

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus-password.txt:/etc/prometheus/prometheus-password.txt
      - prometheus_data:/prometheus
    networks:
      - profissu

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - loki_data:/loki
    networks:
      - profissu

  promtail:
    image: grafana/promtail:3.4.4
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - profissu
    depends_on:
      loki:
        condition: service_started

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - profissu

  app:
    build: .
    container_name: profissu
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILE=dev
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - EMAIL_HOST=maildev
      - EMAIL_PORT=1025
      - EMAIL_USER=
      - EMAIL_PASSWORD=
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    ports:
      - 8081:8081
      - 5005:5005
    volumes:
      - maven_cache:/root/.m2
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      maildev:
        condition: service_healthy
    networks:
      - profissu
    labels:
      logging: "promtail"
      app: "profissu-api"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  profissu:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  maven_cache:
  prometheus_data:
  grafana_data:
  loki_data:
