name: profissu_test

services:
  mysql_test:
    image: mysql:8.1.0
    container_name: profissu_mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_TEST}
      - MYSQL_DATABASE=${MYSQL_DATABASE_TEST}
      - MYSQL_USER=${MYSQL_USER_TEST}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_TEST}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    healthcheck:
      test: 'mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SHOW DATABASES;" || exit 1'
      interval: 10s
      timeout: 5s
    networks:
      - profissu_test_network

  app_test:
    image: maven:3.9.9-amazoncorretto-21-alpine
    container_name: profissu_app_test
    environment:
      - MYSQL_HOST_TEST=mysql_test
      - MYSQL_PORT_TEST=3306
      - MYSQL_DATABASE_TEST=${MYSQL_DATABASE_TEST}
      - MYSQL_USER_TEST=${MYSQL_USER_TEST}
      - MYSQL_PASSWORD_TEST=${MYSQL_PASSWORD_TEST}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - .:/app
      - maven_cache_test:/root/.m2
    working_dir: /app
    restart: "no"
    command: ["mvn", "test", "-Dspring.profiles.active=test"]
    depends_on:
      mysql_test:
        condition: service_healthy
    networks:
      - profissu_test_network

networks:
  profissu_test_network:
    driver: bridge

volumes:
  mysql_data_test:
  maven_cache_test:
