spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_TEST}:${MYSQL_PORT_TEST}/${MYSQL_DATABASE_TEST}
    username: ${MYSQL_USER_TEST}
    password: ${MYSQL_PASSWORD_TEST}
  liquibase:
    drop-first: true
  cache:
    type: none
  data:
    redis:
      host: localhost
      port: 0
      password: ""
  mail:
    host: localhost
    port: 0
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8082

profissu:
  url: http://localhost:8082
  allowed-origins:
    - http://127.0.0.1:3000
    - http://127.0.0.1:5500
