spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_TEST}:${MYSQL_PORT_TEST}/${MYSQL_DATABASE_TEST}
    username: ${MYSQL_USER_TEST}
    password: ${MYSQL_PASSWORD_TEST}
  liquibase:
    drop-first: true
  cache:
    type: none
  data:
    redis:
      host: localhost
      port: 0
      password: ""
  mail:
    host: ${EMAIL_HOST_TEST}
    port: ${EMAIL_PORT_TEST}
    username: ${EMAIL_USER_TEST}
    password: ${EMAIL_PASSWORD_TEST}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8082

profissu:
  url: http://localhost:8082
