spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST_TEST}:${MYSQL_PORT_TEST}/${MYSQL_DATABASE_TEST}
    username: ${MYSQL_USER_TEST}
    password: ${MYSQL_PASSWORD_TEST}
  liquibase:
    drop-first: true
