spring:
  application:
    name: profissu
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  prometheus:
    metrics:
      export:
        enabled: true

profissu:
  jwt:
    expires-in: 300
    private-key-location: classpath:profissu.key
    public-key-location: classpath:profissu.pub
  token:
    expires-in: 1
  url: https://profissu-api.conectabyte.com.br
  allowed-origins:
    - https://conectabyte.com.br
