name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: profissu
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7.4.2
        env:
          REDIS_PASSWORD: admin
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli -h redis -p 6379 -a admin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h 127.0.0.1 -P 3307 --silent; do
            sleep 2
          done

      - name: Grant privileges and create test database
        run: |
          mysql -u root -proot -h 127.0.0.1 -P 3307 -e "CREATE DATABASE profissu_test;"
          mysql -u root -proot -h 127.0.0.1 -P 3307 -e "GRANT ALL PRIVILEGES ON profissu_test.* TO 'admin'@'%';"
          mysql -u root -proot -h 127.0.0.1 -P 3307 -e "FLUSH PRIVILEGES;"

      - name: Install openssl
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Tests
        env:
          MYSQL_HOST_TEST: 127.0.0.1
          MYSQL_PORT_TEST: 3307
          MYSQL_DATABASE_TEST: profissu_test
          MYSQL_USER_TEST: admin
          MYSQL_PASSWORD_TEST: admin
        run: |
          openssl genrsa -out src/main/resources/profissu.key 4096 && \
          openssl rsa -in src/main/resources/profissu.key -pubout -out src/main/resources/profissu.pub
          mvn test

      - name: Build
        env:
          SPRING_PROFILE: dev
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3307
          MYSQL_DATABASE: profissu
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
          REDIS_PASSWORD: admin
        run: |
          openssl genrsa -out src/main/resources/profissu.key 4096 && \
          openssl rsa -in src/main/resources/profissu.key -pubout -out src/main/resources/profissu.pub
          mvn clean package -DskipTests
